# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11service_api.proto\x12\x0bservice_api\"{\n\x14ThermostatApiRequest\x12.\n\x0crequest_type\x18\x01 \x01(\x0e\x32\x18.service_api.RequestType\x12\x17\n\x0fset_temperature\x18\x02 \x01(\x02\x12\x1a\n\x12time_resolution_ms\x18\x03 \x01(\r\"Q\n\x15ThermostatApiResponse\x12\'\n\x06status\x18\x01 \x01(\x0e\x32\x17.service_api.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t*\"\n\x0bRequestType\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01*&\n\nStatusCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32o\n\x11ThermostatService\x12Z\n\x11\x43ontrolThermostat\x12!.service_api.ThermostatApiRequest\x1a\".service_api.ThermostatApiResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTTYPE._serialized_start=242
  _REQUESTTYPE._serialized_end=276
  _STATUSCODE._serialized_start=278
  _STATUSCODE._serialized_end=316
  _THERMOSTATAPIREQUEST._serialized_start=34
  _THERMOSTATAPIREQUEST._serialized_end=157
  _THERMOSTATAPIRESPONSE._serialized_start=159
  _THERMOSTATAPIRESPONSE._serialized_end=240
  _THERMOSTATSERVICE._serialized_start=318
  _THERMOSTATSERVICE._serialized_end=429
# @@protoc_insertion_point(module_scope)
