name: on PR to main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug
  PROJECT_ROOT_PATH: /project
  PROJECT_BUILD_PATH: /project/build
  NETWORK_SSID: TEST_SSID
  NETWORK_PASSWORD: TEST_PASSWORD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: build dev image
      working-directory: ${{github.workspace}}
      id: build-dev-image
      run: |
        docker build --network=host -t esp-dev:latest -f docker/dev.dockerfile .

    - name: build app
      working-directory: ${{github.workspace}}
      run: |
        docker run -i -v ${{github.workspace}}:/project esp-dev:latest bash -c "cmake -B $PROJECT_BUILD_PATH -S $PROJECT_ROOT_PATH -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DNETWORK_SSID=$NETWORK_SSID -DNETWORK_PASSWORD=$NETWORK_PASSWORD && cmake --build $PROJECT_BUILD_PATH --target esp_mcu_server.elf"